/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nitok.jitsu.gradle

import org.assertj.core.api.Assertions.assertThat
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Test

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class JitsuPluginTest {
    @Test fun `lib-plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("eu.nitok.jitsu-lib")

        // Verify the result
        assertThat(project.tasks.findByName("compileTestJitsu")).isNotNull()
        assertThat(project.tasks.findByName("compileMainJitsu")).isNotNull()
        assertThat(project.tasks.findByName("compileJitsu")).isNotNull()
    }

    @Test fun `app-plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("eu.nitok.jitsu-app")

        // Verify the result
        assertThat(project.tasks.findByName("compileMainJitsu")).isNotNull()
        assertThat(project.tasks.findByName("compileJitsu")).isNotNull()
        assertThat(project.tasks.findByName("compileTestJitsu")).isNotNull()
    }
}
