/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("eu.nitok.jitsu.kotlin-library-conventions")
}

dependencies {
    api("com.niton.jainparse:tokenizer")
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
    kapt("info.picocli:picocli-codegen:4.6.1")
    implementation("info.picocli:picocli:4.6.1")
}

