/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("eu.nitok.jitsu.kotlin-library-conventions")
    id("org.jetbrains.kotlin.plugin.serialization") version "1.9.20"
}

dependencies {
    api("com.niton.jainparse:tokenizer")
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
}
