/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nitok.jitsu.gradle

import eu.nitok.jitsu.gradle.tasks.CreateModuleInfo
import eu.nitok.jitsu.gradle.tasks.JitsuCompile
import eu.nitok.jitsu.gradle.tasks.JitsuTranspile
import org.gradle.api.NamedDomainObjectProvider
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.Configuration
import org.gradle.api.artifacts.ConsumableConfiguration
import org.gradle.api.file.SourceDirectorySet
import org.gradle.api.plugins.BasePlugin
import org.gradle.api.tasks.TaskProvider
import org.gradle.language.cpp.CppComponent
import org.gradle.language.cpp.CppLibrary
import org.gradle.language.cpp.ProductionCppComponent
import org.gradle.language.cpp.plugins.CppBasePlugin
import org.gradle.nativeplatform.Linkage

internal const val DEFAULT_C_OUTPUT = "generated/jitsu-c"

/**
 * A simple 'hello world' plugin.
 */
class JitsuBasePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.plugins.apply(BasePlugin::class.java)
        project.plugins.apply(CppBasePlugin::class.java)
        project.dependencies.attributesSchema.attribute(nativeArtifactKind)
        project.dependencies.attributesSchema.attribute(artifactType)

        val extension = project.extensions.create("jitsu", JitsuExtension::class.java).also {
            it.moduleName.convention(project.name)
        }

        extension.sourceSets.whenObjectAdded {
            project.registerJitsuSourceSet(it, extension)
        }

        val main = extension.sourceSets.register(MAIN_SOURCESET_NAME)
        val test = extension.sourceSets.register(TEST_SOURCESET_NAME)

        project.createConsumableArtifact(test, testFixtureCapability)


        project.tasks.register("compileJitsu") {
            it.dependsOn(main.get().compileTask)
        }
        project.tasks.register("transpileJitsu") {
            it.dependsOn(main.get().transpileTask)
        }
        project.tasks.register("createJitsuModuleInfo") {
            it.dependsOn(extension.sourceSets.map { it.moduleInfoTask })
        }
    }

}

internal const val testFixtureCapability: String = "testfixtures"


fun Project.createConsumableArtifact(
    sourceSet: NamedDomainObjectProvider<JitsuSourceSet>,
    capability: String? = null
): NamedDomainObjectProvider<ConsumableConfiguration> {
    return configurations.consumable("${sourceSet.name}JitsuElements") {
        it.extendsFrom(sourceSet.get().moduleClasspath.get())
        it.attributes.attribute(artifactType, JitsuArtifactType.IR)
        it.outgoing.artifact(sourceSet.get().compileTask.flatMap { it.targetFile })
        if(capability != null) it.outgoing.capability(createCapability(capability))
    }
}
internal fun Project.setupNativeBindings(
    sourceSetName: String,
    transpileTask: TaskProvider<JitsuTranspile>,
    dependencies: Configuration
): CppLibrary {
    val cppCreator = project.objects.newInstance(CppLibraryCreator::class.java)

    val cBindingsSourceDirs: SourceDirectorySet = objects.sourceDirectorySet(sourceSetName, "$sourceSetName C bindings")
    cBindingsSourceDirs.filter.include("**/*.c")
    cBindingsSourceDirs.srcDir("src/${sourceSetName}/c")

    val library = cppCreator.createCppLibrary(
        project,
        "${sourceSetName}-bindings",
        publishedArtifactKind = BINDINGS_NATIVE_ARTIFACT,
        publishedCapability = if (sourceSetName == TEST_SOURCESET_NAME) testFixtureCapability else null
    )
    library.linkage.set(setOf(Linkage.STATIC))
    library.source.setFrom(cBindingsSourceDirs)
    library.publicHeaders.from(transpileTask.map { it.targetDirectory.dir("bindings") })
    library.implementationDependencies.extendsFrom(dependencies)


    library.binaries.configureEach { binary ->
        binary.compileTask.get().apply {
            source.setFrom(library.source)
            dependsOn(transpileTask)
        }
    }

    return library
}

internal fun Project.registerJitsuSourceSet(
    sourceSet: JitsuSourceSet,
    extension: JitsuExtension
) {
    val sourceSetName =
        if (sourceSet.name == "main") extension.moduleName else extension.moduleName.map { "$it.${sourceSet.name}" }

    val dependencies = configurations.dependencyScope(sourceSet.dependencyScopeName)
    val bindingDependencies = configurations.dependencyScope(sourceSet.nativeDependencyScopeName)

    val jitsuClasspath = configurations.resolvable(sourceSet.moduleClasspathName) {
        it.extendsFrom(dependencies.get())
        it.attributes.attribute(artifactType, JitsuArtifactType.IR)
    }

    val compileTask = tasks.register(sourceSet.compileTaskName, JitsuCompile::class.java) {
        it.dependencies.from(jitsuClasspath)
        it.sources.setFrom(sourceSet.jistuSources)
        it.moduleName.set(sourceSetName)
        it.targetFile.set(sourceSetName.flatMap { project.layout.buildDirectory.file("modules/$it.jim") })
    }
    val transpileCTask = tasks.register(sourceSet.transpileTaskName, JitsuTranspile::class.java) {
        it.dependencies.setFrom(jitsuClasspath)
        it.moduleFile.set(layout.file(compileTask.map { it.outputs.files.singleFile }))
        it.targetDirectory.set(project.layout.buildDirectory.dir("$DEFAULT_C_OUTPUT/${sourceSet.name}"))
    }

    tasks.register(sourceSet.moduleInfoTaskName, CreateModuleInfo::class.java) {
        it.moduleName.set(sourceSetName)
        it.moduleDir.set(sourceSet.jistuSources.sourceDirectories.singleFile)
    }
    sourceSet.nativeBindings = setupNativeBindings(sourceSet.name, transpileCTask, bindingDependencies.get())
}

internal fun CppComponent.attachBindings(sourceSet: JitsuSourceSet) {

    val bindings = sourceSet.nativeBindings
    source.from(bindings.source)
    privateHeaders.from(bindings.publicHeaders)
    implementationDependencies.extendsFrom(bindings.implementationDependencies)
    fun attachDependencyBindings(config: Configuration?) {
        val bindingRestricted = config?.copy()
        bindingRestricted?.attributes?.attribute(nativeArtifactKind, BINDINGS_NATIVE_ARTIFACT)
        bindingRestricted?.extendsFrom(sourceSet.dependencyScope.get())
        config?.extendsFrom(bindingRestricted)
    }

    binaries.configureEach { binary ->
        attachDependencyBindings(binary.compileIncludePath as? Configuration)
        attachDependencyBindings(binary.runtimeLibraries as? Configuration)
        attachDependencyBindings(binary.linkLibraries as? Configuration)
        binary.compileTask.get().apply {
            source.setFrom(this@attachBindings.source)
            dependsOn(sourceSet.transpileTask)
        }
    }
}
internal fun JitsuSourceSet.setupNativeCompilation(
    cppComponent: ProductionCppComponent,
    project: Project
) {
    val cSourceDirectory: SourceDirectorySet = project.objects.sourceDirectorySet(
        name,
        "$name generated C sources"
    )
    cSourceDirectory.filter.include("**/*.c")
    cSourceDirectory.srcDir(transpileTask.map { it.targetDirectory })
    nativeCompilation = cppComponent
    cppComponent.source.setFrom(cSourceDirectory)
    cppComponent.privateHeaders.setFrom(transpileTask.map { it.targetDirectory })
    cppComponent.attachBindings(this)
}