/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nitok.jitsu.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project

class JitsuLibPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.plugins.apply(JitsuBasePlugin::class.java)

        val extension = project.extensions.getByType(JitsuExtension::class.java)

        val main = extension.sourceSets.main
        project.createConsumableArtifact(main)
        project.setupNativeLibraryCompilation(main.get())
    }

    private fun Project.setupNativeLibraryCompilation(
        sourceSet: JitsuSourceSet
    ) {
        val cppCreator = project.objects.newInstance(CppLibraryCreator::class.java)
        val library = cppCreator.createCppLibrary(this, sourceSet.name)
        library.publicHeaders.from(sourceSet.transpileTask.map { it.targetDirectory.dir("publicHeaders") })
        sourceSet.setupNativeCompilation(library, this)
    }
}
