/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nitok.jitsu.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.SourceDirectorySet
import org.gradle.language.cpp.CppApplication
import org.gradle.language.cpp.ProductionCppComponent
import org.gradle.language.cpp.plugins.CppApplicationPlugin

/**
 * Builds a Jitsu module as a native executable.
 */
class JitsuAppPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.plugins.apply(JitsuBasePlugin::class.java)
        project.plugins.apply(CppApplicationPlugin::class.java)

        val extension = project.extensions.getByType(JitsuExtension::class.java)

        val cppApp = project.extensions.getByType(CppApplication::class.java)
        extension.sourceSets.main.get().setupNativeCompilation(cppApp, project)
    }
}
