/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nitok.jitsu.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class JitsuAppPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.plugins.apply(JitsuBasePlugin::class.java)
    }
}
