/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nitok.jitsu.gradle

import eu.nitok.jitsu.gradle.tasks.CreateModuleInfo
import eu.nitok.jitsu.gradle.tasks.JitsuCompile
import eu.nitok.jitsu.gradle.tasks.JitsuTranspile
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.SourceDirectorySet
import org.gradle.api.plugins.BasePlugin
import org.gradle.api.provider.Provider
import org.gradle.internal.extensions.stdlib.capitalized

@OptIn(ExperimentalSerializationApi::class)
val json: Json = Json(
    builderAction = {
        prettyPrint = true;
        classDiscriminator = "class"
//        namingStrategy = JsonNamingStrategy { _, _, serialName -> serialName.split(".").last() }
//        useArrayPolymorphism = true
    }
)

/**
 * A simple 'hello world' plugin.
 */
class JitsuBasePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.plugins.apply(BasePlugin::class.java)

        val extension = project.extensions.create("jitsu", JitsuExtension::class.java).also {
            it.moduleName.convention(project.name)
        }

        val main = project.registerJitsuSourceSet("main", extension, consumable = true)
        val test = project.registerJitsuSourceSet("test", extension, consumable = false)

        project.tasks.findByName("build")?.dependsOn(main.map { it.transpileTasks })
        project.tasks.register("compileJitsu") {
            it.dependsOn(main.map { it.compileTask })
        }
        project.tasks.register("transpileJitsu") {
            it.dependsOn(main.map { it.transpileTasks })
        }
        project.tasks.register("createJitsuModuleInfo") {
            it.dependsOn(extension.sourceSets.map { it.moduleInfoTask })
        }
    }

    internal fun Project.registerJitsuSourceSet(string: String, extension: JitsuExtension, consumable: Boolean): Provider<JitsuSourceSet> {
        val sourceDirectory: SourceDirectorySet = objects.sourceDirectorySet(string, "$string Jitsu source")
        sourceDirectory.filter.include("**/*.jit")
        sourceDirectory.srcDir("src/${string}/jitsu")

        val sourceSetName = if(string == "main") extension.moduleName else extension.moduleName.map { "$it.$string" }

        val dependencies = configurations.dependencyScope("jitsu${string.capitalized()}")
        val classpath = configurations.resolvable("${string}JitsuClasspath") {
            it.extendsFrom(dependencies.get())
            it.attributes.attribute(artifactType, JitsuArtifactType.IR)
        }

        val compileTask = tasks.register("compile${string.capitalized()}Jitsu", JitsuCompile::class.java) {
            it.dependencies.from(classpath)
            it.sources.setFrom(sourceDirectory)
            it.moduleName.set(sourceSetName)
            it.targetFile.set(project.layout.buildDirectory.file("modules/$string.jim"))
        }
        val transpileCTask = tasks.register("transpile${string.capitalized()}JitsuToC", JitsuTranspile::class.java) {
            it.dependencies.setFrom(classpath)
            it.moduleFile.set(layout.file(compileTask.map { it.outputs.files.singleFile }))
//            it.backend.set(CBackend())
            it.targetDirectory.set(project.layout.buildDirectory.dir("generated/jitsu-c"))
        }

        val moduleInfoTask = tasks.register("createJitsu${string.capitalized()}ModuleInfo", CreateModuleInfo::class.java) {
            it.moduleName.set(sourceSetName)
            it.moduleDir.set(sourceDirectory.sourceDirectories.singleFile)
        }
        if(consumable) {
            val elements = configurations.consumable("${string}JitsuElements") {
                it.extendsFrom(dependencies.get())
                it.attributes.attribute(artifactType, JitsuArtifactType.IR)
            }
            val c_elements = configurations.consumable("${string}JitsuCElements") {
                it.extendsFrom(dependencies.get())
                it.attributes.attribute(artifactType, JitsuArtifactType.C)
            }
            artifacts.add(elements.name, compileTask.flatMap { it.targetFile })
            artifacts.add(c_elements.name, transpileCTask.flatMap { it.targetDirectory })
        }

        val sourceSetProvider = provider {
            JitsuSourceSet(
                sourceDirectory = sourceDirectory,
                compileTask = compileTask,
                transpileTasks = listOf(transpileCTask),
                moduleInfoTask = moduleInfoTask,
                classpath = classpath,
                dependencyScope = dependencies
            )
        }
        extension.sourceSets.addLater(sourceSetProvider)
        return sourceSetProvider
    }
}
